### ISSUE TITLE
Machine Broke

### ISSUE THREAD

**Issue by Silentassassin22** [DoubleLabyrinth/MobaXterm-keygen#11]
File "D:\Program Files\Rockstar Games\Grand Theft Auto V\scripts\MobaXterm-Keygen.py", line 12
    def VariantBase64Encode(bs : bytes):
'''''''''''''''''''''''''''''''''''''''''''''''''''''''''^
SyntaxError: invalid syntax

**Comment by DoubleLabyrinth** [comment]
What is your python version?

**Comment by Silentassassin22** [comment]
I fixed it, you should really say it needs to be python 3
