### ISSUE TITLE
Not working with 12.3

### ISSUE THREAD

**Issue by renzzla** [DoubleLabyrinth/MobaXterm-keygen#14]
Just downloaded and installed MobaXterm 12.3 and generated a new Custom.mxtpro, but the app no longer shows that it's registered. Would be great of you could do a fix for it...Thanks

**Comment by DoubleLabyrinth** [comment]
But keygen works fine on my machine:

![image](https://user-images.githubusercontent.com/16631994/66701869-8317c980-ed33-11e9-979d-fc4db8d986d4.png)

Do you specify a correct version when you use `MobaXterm-Keygen.py`?

**Comment by renzzla** [comment]
Actually, it does for me now too. Previously, I had generated it on Windows 7/Python 3.6.5, but I've just tried again on Windows 10/Python 3.7.4 and it now works.

Thanks for testing it for me.
