### ISSUE TITLE
什么时候能支持12.x版本？

### ISSUE THREAD

**Issue by lrj2u** [DoubleLabyrinth/MobaXterm-keygen#15]
新版本已经出到12.3了，这个keygen已经失效。作者有空能支持更新下吗？谢谢。

**Comment by DoubleLabyrinth** [comment]
你确定你在使用kegne的时候输入了正确的版本号吗？

**Comment by lrj2u** [comment]
> 你确定你在使用kegne的时候输入了正确的版本号吗？

不好意思，是我搞错了，用了旧版本的key文件
