### ISSUE TITLE
Custom.mxtpro文件

### ISSUE THREAD

**Issue by Growing048** [DoubleLabyrinth/MobaXterm-keygen#3]
如果没有正确的Custom.mxtpro文件 怎么入手分析呢

**Comment by DoubleLabyrinth** [comment]
在分析这个软件的时候我也是找到了一份有效的Custom.mxtpro。
来源于http://softoroom.net/topic87006.html
标题为`MobaXterm Pro 11 + crack (license)`的那一个

剩下的就很容易了，追踪这个文件的处理过程即可

**Comment by dupeng0811** [comment]
大佬有支持版本11的计划么，今天去下载竟然发现官方出了V 11了 ，

**Comment by DoubleLabyrinth** [comment]
@dupeng0811 
keygen是支持v11版本的

**Comment by wenxingyu** [comment]
我下载并安装了v11版本，参照文中的方式一直无法激活v11 build 3816，莫非有算法更新？

**Comment by wenxingyu** [comment]
> 我下载并安装了v11版本，参照文中的方式一直无法激活v11 build 3816，莫非有算法更新？

版本号写错了。。。

**Comment by Tgkplvfy** [comment]
只能安装installer版本，还是portable版本也可以？

**Comment by Tgkplvfy** [comment]
> 只能安装installer版本，还是portable版本也可以？

好了好了，portable也可以。重启了一下生效了。并且自动识别了，securecrt里的session。

**Comment by nankingrider** [comment]
感谢大佬。 ！ 帮了大忙~~
