### ISSUE TITLE
怎样合并Custom.mxtpro和MobaXterm customization.custom？

### ISSUE THREAD

**Issue by Reguse** [DoubleLabyrinth/MobaXterm-keygen#4]
用cat命令或zip重新打包，都不起作用，正确的合并方式应该是什么？

**Comment by DoubleLabyrinth** [comment]
将这两个文件解压之后，文件全部放到一起打包。注意压缩包的根目录下就应该是`Custom.mxtpro`和`MobaXterm customization.custom`里的文件

**Comment by Reguse** [comment]
成功了，非常感谢
