### ISSUE TITLE
求助： 安装了python27_4960，运行MobaXterm-Keygen.py无任何显示，再次执行提升SyntaxError

### ISSUE THREAD

**Issue by alphayi** [DoubleLabyrinth/MobaXterm-keygen#5]
e:\Software\Develop\MobaXterm_Portable_v10.9\MobaXterm-keygen-master>MobaXterm-Keygen.py "BetaAi" 10.9

e:\Software\Develop\MobaXterm_Portable_v10.9\MobaXterm-keygen-master>MobaXterm-Keygen.py "BetaAi" 10.9
  File "E:\Software\Develop\MobaXterm_Portable_v10.9\MobaXterm-keygen-master\MobaXterm-Keygen.py", line 12
    def VariantBase64Encode(bs : bytes):
                               ^
SyntaxError: invalid syntax

**Comment by DoubleLabyrinth** [comment]
这是python3脚本，请麻烦安装python3再试

**Comment by vrathore18** [comment]
Not working.

**Comment by aristotaly** [comment]
> Not working.
try using  python 3.7 :)

**Comment by horizonl** [comment]
需要装python3的，python2和python3有点差别所以没法运行
