### ISSUE TITLE
Python 3.7.1执行报错

### ISSUE THREAD

**Issue by Nidhoggur1993** [DoubleLabyrinth/MobaXterm-keygen#6]
如图
![image](https://user-images.githubusercontent.com/12947582/52756134-57750000-303b-11e9-8716-d7945083064b.png)
这个要怎么解决呢？

**Comment by DoubleLabyrinth** [comment]
很明显python脚本中混入了xml语言的东西。我不知道你是怎么下载的，请确保脚本是正确的再试。

**Comment by Nidhoggur1993** [comment]
确实是IDM下载时导致的问题，已经解决了，感谢。
