### ISSUE TITLE
help: Please help to see what's the problem

### ISSUE THREAD

**Issue by sharpbladepan** [DoubleLabyrinth/MobaXterm-keygen#7]
D:\tmp>.\MobaXterm-Keygen.py "abc" 11.1

D:\tmp>
[main 2019-03-30T02:08:12.727Z] update#setState idle
[main 2019-03-30T02:08:42.728Z] update#setState checking for updates
[main 2019-03-30T02:08:47.575Z] update#setState idle

Above is the screen in my win10. When running the cli, also the py source file is opened in VS code automatically.

**Comment by DoubleLabyrinth** [comment]
It seems that your system does not associate .py file with python interpreter.
Maybe you can try this
```
python .\MobaXterm-Keygen.py "abc" 11.1
```

**Comment by sharpbladepan** [comment]
It's my mistake. All right now.
Thanks!
