### ISSUE TITLE
0

### ISSUE THREAD

**Issue by donald005** [DoubleLabyrinth/MobaXterm-keygen#9]
d:> python MobaXterm-Keygen.py "donald" 11.1
  File "MobaXterm-Keygen.py", line 7
    <.!DOCTYPE html>
    ^
SyntaxError: invalid syntax

**Comment by DoubleLabyrinth** [comment]
see #6

**Comment by afwn90cj93201nixr2e1re** [comment]
@DoubleLabyrinth check email.

**Comment by DoubleLabyrinth** [comment]
@afwn90cj93201nixr2e1re 
I'm sorry. What emal? I've checked my mailbox, nothing special was found.

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/63693169-675c7080-c824-11e9-8d06-9e974eff4dc8.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/63693232-9377f180-c824-11e9-836e-c2ea8ca67cb2.png)
Is that your emails?
@DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
@afwn90cj93201nixr2e1re 
Yes, both of two email address are mine. But there's no new email. Could you send the email again?
Or you can send the email to xiaoaiyu007@gmail.com.

**Comment by afwn90cj93201nixr2e1re** [comment]
duplicated 2 times to gmail.
@DoubleLabyrinth

**Comment by DoubleLabyrinth** [comment]
@afwn90cj93201nixr2e1re 
Ok. I received your emails. I'll contact you via xiao_ai_yu@live.cn later.
